name: Weekly Dutch FRBR Crawl

on:
  schedule:
    - cron: '0 3 * * 0'   # every Sunday at 03:00 UTC
  workflow_dispatch:     # manual trigger

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          # Use a maintained Python version
          python-version: '3.11'

      - name: Verify Python version
        run: python --version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run pipeline
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python step1_collect_urls.py
          python step2_download_items.py
          python step3_clean_text.py
          python step4_upload_shards.py --token $HF_TOKEN
