name: Scrape and Upload Lokale Bekendmakingen

on:
  workflow_dispatch:

jobs:
  scrape-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run scraper
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        python scrape.py
