name: Scrape Officiële Publicaties

on:
  workflow_dispatch:        # manual trigger
  schedule:
    - cron: "30 2 * * *"    # every night at 02:30 UTC (≈ after event file is published)

permissions:
  contents: write           # allow committing to the repo
  id-token: write

env:
  PYTHONUNBUFFERED: "1"      # show log lines as they happen

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}   # add this secret in repo settings
        run: python scraper.py

      - name: Commit & push dataset file
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/officielepublicaties.jsonl
          git commit -m "Automatic update $(date -u '+%Y-%m-%d')" || echo "No changes"
          git push
